##############################################################################
# This file holds configuration parameters for the creation of this dataset. #
##############################################################################

# Filter settings
attributes:
  {"EinheitMastrNummer": "mastr_id",
   "EinheitBetriebsstatus": "status",
   "LokationMastrNummer": "mastr_location_id",
   "Postleitzahl": "zip_code",
   "Ort": "city",
   "Laengengrad": "lon",
   "Breitengrad": "lat",
   "Inbetriebnahmedatum": "commissioning_date",
   "GeplantesInbetriebnahmedatum": "commissioning_date_planned",
   "DatumEndgueltigeStilllegung": "decommissioning_date",
   "NameStromerzeugungseinheit": "name",
   "NameWindpark": "name_park",
   "Bruttoleistung": "capacity_gross",
   "Nettonennleistung": "capacity_net",
   "Lage": "site_type",
   "Hersteller": "manufacturer_name",
   "Typenbezeichnung": "type_name",
   "Nabenhoehe": "hub_height",
   "Rotordurchmesser": "rotor_diameter",
   "AuflageAbschaltungLeistungsbegrenzung": "constraint_deactivation_sound_emission",
   "AuflagenAbschaltungSchallimmissionsschutzNachts": "constraint_deactivation_sound_emission_night",
   "AuflagenAbschaltungSchallimmissionsschutzTagsueber": "constraint_deactivation_sound_emission_day",
   "AuflagenAbschaltungSchattenwurf": "constraint_deactivation_shadowing",
   "AuflagenAbschaltungTierschutz": "constraint_deactivation_animals",
   "AuflagenAbschaltungEiswurf": "constraint_deactivation_ice",
   "Buergerenergie": "citizens_unit",
   "NetzbetreiberpruefungStatus": "validated_by_system_operator"}
attributes_filter:
  {"Land": "Deutschland",
   "EinheitBetriebsstatus": ["In Betrieb", "In Planung"],
   "Lage": "Windkraft an Land"}

# Output settings
layer: bnetza_mastr_wind
