##############################################################################
# This file holds configuration parameters for the creation of this dataset. #
##############################################################################

# Area names (which identify files from preprocessing)
areas:
  [
    "stp_2018_eg",
    "stp_2024_vr"
  ]

# Attributes' captions for the app
captions:
  {"weg_nr": "WEG Nummer",
   "weg_name": "WEG Name",
   "vr_wen_nr": "VR WEN Nummer"}
