##############################################################################
# This file holds configuration parameters for the creation of this dataset. #
##############################################################################

# Filter settings
attributes:
  {"EinheitMastrNummer": "mastr_id",
   "KwkMastrNummer": "kwk_mastr_id",
   "EinheitBetriebsstatus": "status",
   "LokationMastrNummer": "mastr_location_id",
   "Postleitzahl": "zip_code",
   "Ort": "city",
   "Laengengrad": "lon",
   "Breitengrad": "lat",
   "Inbetriebnahmedatum": "commissioning_date",
   "GeplantesInbetriebnahmedatum": "commissioning_date_planned",
   "DatumEndgueltigeStilllegung": "decommissioning_date",
   "NameStromerzeugungseinheit": "name",
   "Nettonennleistung": "capacity_net",
   "Bruttoleistung": "capacity_gross",
   "ArtDerWasserkraftanlage": "plant_type",
   "ArtDesZuflusses": "water_origin",
   "Einspeisungsart": "feedin_type",
   "NetzbetreiberpruefungStatus": "validated_by_system_operator"}
attributes_filter:
  {"Land": "Deutschland",
   "EinheitBetriebsstatus": ["In Betrieb", "In Planung"],
   "Landkreis": ["Wittenberg", "Anhalt-Bitterfeld", "Dessau-Roßlau"]}

# Output settings
layer: bnetza_mastr_hydro
