##############################################################################
# This file holds configuration parameters for the creation of this dataset. #
##############################################################################

# Name of the dataset (used e.g. for report purposes)
title:
  Region ABW

# Description of this dataset
description:
  Region ABW aus Geodaten der Verwaltungsgebiete zusammengeführt.
