##############################################################################
# This file holds configuration parameters for the creation of this dataset. #
##############################################################################

# Map list for right panel
map_panel_layer_list:
  boundaries:
    [
      "bkg_vg250_districts_region",
      "bkg_vg250_muns_region"
    ]
  energy:
    [
      "bnetza_mastr_wind_agg_region",
      "bnetza_mastr_pv_ground_agg_region",
      "bnetza_mastr_pv_roof_agg_region",
      "bnetza_mastr_biomass_agg_region",
      "bnetza_mastr_hydro_agg_region",
      "bnetza_mastr_combustion_agg_region",
      "bnetza_mastr_gsgk_agg_region",
      "bnetza_mastr_storage_agg_region"
    ]
  settlements_infrastructure:
    [
      "settlement-0m_region",
      "industry_region",
      "road_region",
      "railway_region",
      "road_railway-500m_region",
      "aviation_region",
      "air_traffic_control_system_region",
      "military_region",
      "grid_region"
    ]
  nature_landscape:
    [
      "nature_conservation_area_region",
      "drinking_water_protection_area_region",
      "fauna_flora_habitat_region",
      "special_protection_area_region",
      "biosphere_reserve_region",
      "wetland_ramsar_region",
      "forest_region",
      "water_region",
      "floodplain_region",
      "landscape_protection_area_region",
      "soil_quality_high_region",
      "soil_quality_low_region",
      "less_favoured_areas_agricultural_region"
    ]

# Settings for energy panel
panel_settings:
  energy_settings_panel:
    s_w_1:
      max: 1512
      min: 0
      start: 30
      status_quo: 50
      future_scenario: ### <- TBD
      step: 5
    s_pv_ff_1:
      max: 1200
      min: 0
      start: 30
      status_quo: 50
      step: 5
    s_pv_ff_3:
      max: 100
      min: 0
      start: 0
      step: 5
    s_pv_ff_4:
      max: 100
      min: 0
      start: 0
      step: 5
    s_pv_d_1:
      max: 400
      min: 0
      start: 30
      status_quo: 50
      step: 5
    s_pv_d_3:
      max: 100
      min: 0
      start: 0
      step: 5
    s_pv_d_4:
      max: 100
      min: 0
      start: 0
      step: 5
    s_h_1:
      max: 30
      min: 0
      start: 5
      status_quo: 15
      step: 1
    s_b_1:
      max: 30
      min: 0
      start: 5
      status_quo: 15
      step: 5
    s_v_1:
      max: 210
      min: 50
      start: 50
      status_quo: 50
      step: 10
    s_v_3:
      max: 200
      min: 50
      start: 100
      step: 10
    s_v_4:
      max: 200
      min: 50
      start: 100
      step: 10
    s_v_5:
      max: 200
      min: 50
      start: 100
      step: 10
    s_s_g_1:
      max: 20
      min: 0
      start: 2
      status_quo: 3
      step: 0.1
    s_s_g_3:
      max: 200
      min: 0
      start: 5
      step: 10

  heat_settings_panel:
    w_d_wp_1:
      max: 100
      min: 0
      start: 30
      status_quo: 50
      step: 5
    w_d_wp_3:
      max: 100
      min: 50
      start: 50
      status_quo: 50
      step: 5
    w_d_wp_4:
      max: 100
      min: 50
      start: 50
      status_quo: 50
      step: 5
    w_d_wp_5:
      max: 100
      min: 50
      start: 50
      status_quo: 50
      step: 5
    w_z_wp_1:
      max: 100
      min: 0
      start: 10
      status_quo: 40
      step: 5
    w_z_wp_3:
      max: 200
      min: 50
      start: 50
      status_quo: 100
      step: 5
    w_v_1:
      max: 100
      min: 50
      start: 10
      status_quo: 40
      step: 10
    w_v_3:
      max: 200
      min: 50
      start: 50
      status_quo: 100
      step: 10
    w_v_4:
      max: 200
      min: 50
      start: 10
      status_quo: 100
      step: 10
    w_v_5:
      max: 200
      min: 50
      start: 50
      status_quo: 100
      step: 10
    w_d_s_1:
      max: 200
      min: 25
      start: 25
      status_quo: 100
      step: 5
    w_d_s_3:
      max: 200
      min: 25
      start: 25
      status_quo: 100
      step: 5
    w_z_s_1:
      max: 200
      min: 25
      start: 25
      status_quo: 100
      step: 5
    w_z_s_3:
      max: 200
      min: 25
      start: 25
      status_quo: 100
      step: 5

  traffic_settings_panel:
    v_iv_1:
      max: 100
      min: 0
      start: 30
      status_quo: 50
      step: 5
    v_iv_3:
      max: 100
      min: 0
      start: 25
      status_quo: 45
      step: 5
