##############################################################################
# This file holds configuration parameters for the creation of this dataset. #
##############################################################################

# Map list for right panel
map_panel_layer_list:
  boundaries:
    [
      "bkg_vg250_districts_region",
      "bkg_vg250_muns_region"
    ]
  energy:
    [
      "bnetza_mastr_wind_agg_region",
      "bnetza_mastr_pv_ground_agg_region",
      "bnetza_mastr_pv_roof_agg_region",
      "bnetza_mastr_biomass_agg_region",
      "bnetza_mastr_hydro_agg_region",
      "bnetza_mastr_combustion_agg_region",
      "bnetza_mastr_gsgk_agg_region",
      "bnetza_mastr_storage_agg_region"
    ]
  settlements_infrastructure:
    [
      "settlement-0m_region",
      "industry_region",
      "road_region",
      "railway_region",
      "road_railway-500m_region",
      "aviation_region",
      "air_traffic_control_system_region",
      "military_region",
      "grid_region"
    ]
  nature_landscape:
    [
      "nature_conservation_area_region",
      "drinking_water_protection_area_region",
      "fauna_flora_habitat_region",
      "special_protection_area_region",
      "biosphere_reserve_region",
      "wetland_ramsar_region",
      "forest_region",
      "water_region",
      "floodplain_region",
      "landscape_protection_area_region",
      "soil_quality_high_region",
      "soil_quality_low_region",
      "less_favoured_areas_agricultural_region"
    ]
