# TODO: Find out if something needs to be changed in here in comparison to digiplan

exclude: 'docs|node_modules|vendors|migrations|.git|.tox'
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.244'
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--line-length", "80", "black"]

  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        types: [python]
      - id: flake8
        name: flake8
        args:
          - --max-line-length=80
          - --ignore=DAR101,DAR201,F821,DAR401,W503,E800,E722,B001,B008,C408,W605,B007,S101,A003,A001,B023,C417
        entry: flake8
        language: python
        types: [python]
      - id: pylint
        name: pylint
        entry: env DATABASE_URL=null env PROJ_LIB=null USE_DOCKER=null pylint
        language: system
        types: [python]
        args:
          [
            "-rn", # Only display messages
            "-sn", # Don't display the score
            "--disable=E0602", # Disable the E0602 error
            "--disable=C0114", # Disable the C0114 error TODO: To be fixed
            "--disable=C0116", # Disable the C0116 error TODO: To be fixed
            "--disable=R1729", # Disable the R1729 error TODO: To be fixed
            "--disable=C0103", # Disable the C0103 error TODO: To be fixed
            "--disable=R0801", # Disable the R0801 error TODO: To be fixed
            "--disable=W1514", # Disable the W1514 error TODO: To be fixed
            "--disable=R1734", # Disable the R1734 error TODO: To be fixed
            "--disable=R1735", # Disable the R1735 error TODO: To be fixed
            "--disable=W0612", # Disable the W0612 error TODO: To be fixed
            "--disable=W1401", # Disable the W1401 error TODO: To be fixed
            "--disable=W0511", # Disable the W0511 error TODO: To be fixed
            "--disable=R0913", # Disable the R0913 error TODO: To be fixed
            "--disable=R1705", # Disable the R1705 error TODO: To be fixed
            "--disable=E0401", # Disable the E0401 error TODO: To be fixed
            "--disable=E0611", # Disable the E0611 error TODO: To be fixed
            "--disable=W0621", # Disable the W0621 error TODO: To be fixed
            "--disable=W0640", # Disable the W0640 error TODO: To be fixed
            "--disable=C0115", # Disable the C0115 error TODO: To be fixed
            "--disable=R1725", # Disable the R1725 error TODO: To be fixed
            "--disable=R0903", # Disable the R0903 error TODO: To be fixed
            "--disable=C0302", # Disable the C0302 error TODO: To be fixed
            "--disable=W0707", # Disable the W0707 error TODO: To be fixed
            "--disable=W0108", # Disable the W0108 error TODO: To be fixed
            "--disable=W1203", # Disable the W1203 error TODO: To be fixed
            "--disable=W0622", # Disable the W0622 error TODO: To be fixed
            "--disable=R1720", # Disable the R1720 error TODO: To be fixed
            "--disable=R0914", # Disable the R0914 error TODO: To be fixed
            "--disable=R1724", # Disable the R1724 error TODO: To be fixed
            "--disable=W0012", # Disable the W0012 error TODO: To be fixed
            "--disable=W0611", # Disable the W0611 error TODO: To be fixed
            "--disable=C0207", # Disable the C0207 error TODO: To be fixed
            "--max-line-length=80", # Set the maximum line length to 80
          ]
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [python]
        args:
          [
            "--ignore-missing-imports", # Ignore missing imports
            "--warn-unused-ignores", # Warn about unused ignore comments
            "--disable-error-code=name-defined", # To suppress Name "snakemake"
            # is not defined  [name-defined]
            "--disable-error-code=var-annotated",
            "--disable-error-code=var-annotated",
            "--disable-error-code=dict-item",
            "--disable-error-code=arg-type",
            "--disable-error-code=assignment",
            "--disable-error-code=attr-defined",
            "--disable-error-code=index",
            "--disable-error-code=misc",
          ]
