repo_name: rl-institut-private/digipipe
repo_url: https://github.com/rl-institut-private/digipipe
site_name: digipipe 0.0.1 dev documentation
site_url: http://127.0.0.1:8000/
docs_dir: .
site_dir: ./site

nav:
  - Digipipe: index.md
  - Scenarios: docs/sections/scenarios.md
  - Developer Docs (en):
      - Installation: docs/sections/installation.md
      - Data pipeline: docs/sections/data.md
      - Workflow: docs/sections/workflow.md
      - Struktur des Repos: docs/sections/structure.md
  - Datasets:
      - Raw: docs/datasets/raw_datasets.md 
      - Preprocessed: docs/datasets/preprocessed_datasets.md 
      - Datasets: docs/datasets/datasets_datasets.md 

plugins:
  - search:
      lang:
        - en
        - de
  - include-markdown
  - same-dir
  - exclude:
      glob:
        - digipipe/store/
        - digipipe/config/*
        - README.md
        - CHANGELOG.md
        - "*.tmp"
        - "*.pdf"
        - "*.gz"
        - "*.py"
        - "*.pyc"
        - "*.gpkg"
      regex:
        - '.*\.(tmp|bin|tar)$'

theme:
  name: material
  features:
    - navigation.footer
    - navigation.tracking
    - navigation.tabs
    - navigation.instant
    - navigation.indexes
    - navigation.top 
    - content.code.copy
    - toc.follow
    - search.highlight
    - search.suggestions
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - docs/stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.smartsymbols:
      arrows: True
  - toc:
      permalink: "#"
  - admonition
  - pymdownx.details
  - pymdownx.superfences

