##############################################################################
# This file holds configuration parameters for the creation of this dataset. #
##############################################################################

# Files to be extracted from raw dataset
files_extract:
  [
    "T45-Strom_buildings_heating_consumption_by_carrier.csv",
    "T45-Strom_buildings_heating_structure_by_technology.csv",
    "T45-Strom_cts_consumption.csv",
    "T45-Strom_hh_consumption.csv",
    "T45-Strom_ind_consumption.csv"
  ]
