##############################################################################
# This file holds configuration parameters for the creation of this dataset. #
##############################################################################

# Files to be extracted from raw dataset
files_extract:
  [
    "T45-Strom_buildings_heating_demand_by_carrier.csv",
    "T45-Strom_buildings_heating_structure_by_technology.csv",
    "T45-Strom_cts_demand.csv",
    "T45-Strom_hh_demand.csv",
    "T45-Strom_ind_demand.csv",
    "TN-Strom_buildings_heating_demand_by_carrier.csv"
  ]
