##############################################################################
# This file holds configuration parameters for the creation of this dataset. #
##############################################################################

# Files to be clipped to region
files_clip:
  [
    "biosphere_reserve.gpkg",
    "fauna_flora_habitat.gpkg",
    "landscape_protection_area.gpkg",
    #"national_park.gpkg",
    "nature_conservation_area.gpkg",
    #"nature_monument.gpkg",
    "nature_park.gpkg",
    "special_protection_area.gpkg"
  ]
