##############################################################################
# This file holds configuration parameters for the creation of this dataset. #
##############################################################################

# Excel file
excel_file:
  sheet_name:
    {
      "2010": "Gemeindedaten",
      "2015": "Onlineprodukt_Gemeinden_311215",
      "2020": "Onlineprodukt_Gemeinden",
      "2021": "Onlineprodukt_Gemeinden",
      "2022": "Onlineprodukt_Gemeinden",
      "2023": "Onlineprodukt_Gemeinden31122023"
    }
  usecols: "C:E, G, J"
  skiprows: 6
  names:
    [
      "Land",
      "RB",
      "Kreis",
      "Gem",
      "population"
    ]
  dtype:
    {
      "Land": str,
      "RB": str,
      "Kreis": str,
      "Gem": str
    }
