##############################################################################
# This file holds configuration parameters for the creation of this dataset. #
##############################################################################

areas:
  [
    "soil_quality_low",
    "soil_quality_medium",
    "permanent_crops",
  ]

# Delete areas below min. area (in ha (1 ha = 1 cell))
area_threshold: 2

# PV targets split: share of pv_ground
# Caution: when adjusting this value, the pv_roof_share in dataset
#          potentialarea_pv_roof_region must be adjusted accordingly!
pv_ground_share: 0.5
