##############################################################################
# This file holds configuration parameters for the creation of this dataset. #
##############################################################################

# Filter settings
unit_attributes:
  {"EinheitMastrNummer": "mastr_id",
   "EinheitBetriebsstatus": "status",
   "LokationMastrNummer": "mastr_location_id",
   "Postleitzahl": "zip_code",
   "Ort": "city",
   "Laengengrad": "lon",
   "Breitengrad": "lat",
   "Inbetriebnahmedatum": "commissioning_date",
   "GeplantesInbetriebnahmedatum": "commissioning_date_planned",
   "DatumEndgueltigeStilllegung": "decommissioning_date",
   "NameStromerzeugungseinheit": "name",
   "Bruttoleistung": "capacity_gross",
   "Nettonennleistung": "capacity_net",
   "Einspeisungsart": "feedin_type",
   "Einheittyp": "type",
   "Batterietechnologie": "battery_technology",
   "AcDcKoppelung": "ac_dc_coupling",
   "Pumpspeichertechnologie": "pumped_hydro_technology",
   "Notstromaggregat": "emergency_generator",
   "NetzbetreiberpruefungStatus": "validated_by_system_operator"}
unit_attributes_filter:
  {"Land": "Deutschland",
   "EinheitBetriebsstatus": ["In Betrieb", "In Planung"],
   "Landkreis": ["Wittenberg", "Anhalt-Bitterfeld", "Dessau-Roßlau"]}

plant_attributes:
  {"VerknuepfteEinheit": "unit_mastr_id",
   "MastrNummer": "plant_mastr_id",
   "NutzbareSpeicherkapazitaet": "storage_capacity"}

# Output settings
layer: bnetza_mastr_storage
