##############################################################################
# This file holds configuration parameters for the creation of this dataset. #
##############################################################################

# Excel file
excel_file:
  sheet_name: "DE"
  usecols: "A:C"
  dtype:
    {"LAU CODE": str}

column_names:
  ["nuts_code",
   "lau_code",
   "name"]
