##############################################################################
# This file holds configuration parameters for the creation of this dataset. #
##############################################################################

# Files
geodata:
  # Dataset name: [file list]
  rli_pv_wfr_region:
    [
      "air_traffic_control_system_region.gpkg",
      "aviation_region.gpkg",
      "biosphere_reserve_region.gpkg",
      "drinking_water_protection_area_region.gpkg",
      "fauna_flora_habitat_region.gpkg",
      "floodplain_region.gpkg",
      "forest_region.gpkg",
      "grid_region.gpkg",
      "industry_region.gpkg",
      "landscape_protection_area_region.gpkg",
      "less_favoured_areas_agricultural_region.gpkg",
      "military_region.gpkg",
      #"national_park_region.gpkg",
      "nature_conservation_area_region.gpkg",
      "potentialarea_pv_agriculture_lfa-off_region.gpkg",
      "potentialarea_pv_road_railway_region.gpkg",
      "railway_region.gpkg",
      "road_region.gpkg",
      "road_railway-500m_region.gpkg",
      "settlement-0m_region.gpkg",
      #"slope_region.gpkg",
      "soil_quality_high_region.gpkg",
      "soil_quality_low_region.gpkg",
      "special_protection_area_region.gpkg",
      "water_region.gpkg",
      #"wetland_ramsar_region.gpkg"
    ]

  bnetza_mastr_biomass_region:
    ["bnetza_mastr_biomass_agg_region.gpkg"]
  bnetza_mastr_combustion_region:
    ["bnetza_mastr_combustion_agg_region.gpkg"]
  bnetza_mastr_gsgk_region:
    ["bnetza_mastr_gsgk_agg_region.gpkg"]
  bnetza_mastr_hydro_region:
    ["bnetza_mastr_hydro_agg_region.gpkg"]
  bnetza_mastr_pv_ground_region:
    ["bnetza_mastr_pv_ground_agg_region.gpkg"]
  bnetza_mastr_pv_roof_region:
    ["bnetza_mastr_pv_roof_agg_region.gpkg"]
  bnetza_mastr_storage_region:
    ["bnetza_mastr_storage_agg_region.gpkg"]
  bnetza_mastr_wind_region:
    ["bnetza_mastr_wind_agg_region.gpkg"]

  bkg_vg250_districts_region:
    ["bkg_vg250_districts_region.gpkg"]
  bkg_vg250_muns_region:
    ["bkg_vg250_muns_region.gpkg"]
  bkg_vg250_region:
    ["bkg_vg250_region.gpkg"]
