##############################################################################
# This file holds configuration parameters for the creation of this dataset. #
##############################################################################

# Population prognosis: years to be included from country prognosis
# data on federal state level (empty list to deactivate).
# Note: Latest year from historic municipal data will be used as base for
# scaling
prognosis_country_fstatelevel:
  years:
    [
      2025,
      2030,
      2035,
      2040,
      2045
    ]
