##############################################################################
# This file holds configuration parameters for the creation of this dataset. #
##############################################################################

# Filter settings
layer: vg250_gem
attributes:
  {"AGS": "ags",
   "GEN": "name",
   "geometry": "geometry"}
attributes_filter:
  {"GF": 4,
   "NUTS": ["DEE01", "DEE05", "DEE0E"]}
