##############################################################################
# This file holds configuration parameters for the creation of this dataset. #
##############################################################################

# Tags to include (format: [tag, value]))
