##############################################################################
# This file holds configuration parameters for the creation of this dataset. #
##############################################################################

# New column names
rename_columns:
  {
    "Typ": "type",
    "Gebiet": "name",
    "Schlüssel": "ags",
    "Jahr": "year",
    "Sanierungszustand: Neubau Anzahl": "ren_con_new_build_count",
    "Sanierungszustand: Neubau Wärmebedarf (kWh)": "ren_con_new_build_heat_demand",
    "Sanierungszustand: Neubau CO₂-Emission (t CO₂-Äq.)": "renovation_condition_new_build_emission",
    "Sanierungszustand: Neubau Endenergieverbrauch (kWh)": "ren_con_new_build_energy_consumption",
    "Sanierungszustand: Vollsaniert Anzahl": "ren_con_fully_ren_count",
    "Sanierungszustand: Vollsaniert Wärmebedarf (kWh)": "ren_con_fully_ren_heat_demand",
    "Sanierungszustand: Vollsaniert CO₂-Emission (t CO₂-Äq.)": "ren_con_fully_ren_emission",
    "Sanierungszustand: Vollsaniert Endenergieverbrauch (kWh)": "ren_con_fully_ren_energy_consumption",
    "Sanierungszustand: Teilsaniert Anzahl": "ren_con_partly_ren_count",
    "Sanierungszustand: Teilsaniert Wärmebedarf (kWh)": "ren_con_partly_ren_heat_demand",
    "Sanierungszustand: Teilsaniert CO₂-Emission (t CO₂-Äq.)": "ren_con_partly_ren_emission",
    "Sanierungszustand: Teilsaniert Endenergieverbrauch (kWh)": "ren_con_partly_ren_energy_consumption",
    "Sanierungszustand: Unsaniert Anzahl": "ren_con_unren_count",
    "Sanierungszustand: Unsaniert Wärmebedarf (kWh)": "ren_con_unren_heat_demand",
    "Sanierungszustand: Unsaniert CO₂-Emission (t CO₂-Äq.)": "ren_con_unren_emission",
    "Sanierungszustand: Unsaniert Endenergieverbrauch (kWh)": "ren_con_unren_energy_consumption",
    "GebTyp: Industrie Anzahl": "build_type_industry_count",
    "GebTyp: Industrie Wärmebedarf (kWh)": "build_type_industry_heat_demand",
    "GebTyp: Industrie CO₂-Emission (t CO₂-Äq.)": "build_type_industry_emission",
    "GebTyp: Industrie Endenergieverbrauch (kWh)": "build_type_industry_energy_consumption",
    "GebTyp: Nichtwohngebäude Anzahl": "build_type_non_residential_count",
    "GebTyp: Nichtwohngebäude Wärmebedarf (kWh)": "build_type_non_residential_heat_demand",
    "GebTyp: Nichtwohngebäude CO₂-Emission (t CO₂-Äq.)": "build_type_non_residential_emission",
    "GebTyp: Nichtwohngebäude Endenergieverbrauch (kWh)": "build_type_non_residential_energy_consumption",
    "GebTyp: Wohngebäude Anzahl": "build_type_residential_count",
    "GebTyp: Wohngebäude Wärmebedarf (kWh)": "build_type_residential_heat_demand",
    "GebTyp: Wohngebäude CO₂-Emission (t CO₂-Äq.)": "build_type_residential_emission",
    "GebTyp: Wohngebäude Endenergieverbrauch (kWh)": "build_type_residential_energy_consumption",
    "Energieträger: Wärmenetze Anzahl": "energy_carrier_heat_networks_count",
    "Energieträger: Wärmenetze Wärmebedarf (kWh)": "energy_carrier_heat_networks_heat_demand",
    "Energieträger: Wärmenetze CO₂-Emission (t CO₂-Äq.)": "energy_carrier_heat_networks_emission",
    "Energieträger: Wärmenetze Endenergieverbrauch (kWh)": "energy_carrier_heat_networks_energy_consumption",
    "Energieträger: Feste Biomasse Anzahl": "energy_carrier_solid_biomass_count",
    "Energieträger: Feste Biomasse Wärmebedarf (kWh)": "energy_carrier_solid_biomass_heat_demand",
    "Energieträger: Feste Biomasse CO₂-Emission (t CO₂-Äq.)": "energy_carrier_solid_biomass_emission",
    "Energieträger: Feste Biomasse Endenergieverbrauch (kWh)": "energy_carrier_solid_biomass_energy_consumption",
    "Energieträger: Gas Anzahl": "energy_carrier_gas_count",
    "Energieträger: Gas Wärmebedarf (kWh)": "energy_carrier_gas_heat_demand",
    "Energieträger: Gas CO₂-Emission (t CO₂-Äq.)": "energy_carrier_gas_emission",
    "Energieträger: Gas Endenergieverbrauch (kWh)": "energy_carrier_gas_energy_consumption",
    "Energieträger: Kohle Anzahl": "energy_carrier_coal_count",
    "Energieträger: Kohle Wärmebedarf (kWh)": "energy_carrier_coal_heat_demand",
    "Energieträger: Kohle CO₂-Emission (t CO₂-Äq.)": "energy_carrier_coal_emission",
    "Energieträger: Kohle Endenergieverbrauch (kWh)": "energy_carrier_coal_energy_consumption",
    "Energieträger: Öl Anzahl": "energy_carrier_oil_count",
    "Energieträger: Öl Wärmebedarf (kWh)": "energy_carrier_oil_heat_demand",
    "Energieträger: Öl CO₂-Emission (t CO₂-Äq.)": "energy_carrier_oil_emission",
    "Energieträger: Öl Endenergieverbrauch (kWh)": "energy_carrier_oil_energy_consumption",
    "Energieträger: Strom Anzahl": "energy_carrier_electricity_count",
    "Energieträger: Strom Wärmebedarf (kWh)": "energy_carrier_electricity_heat_demand",
    "Energieträger: Strom CO₂-Emission (t CO₂-Äq.)": "energy_carrier_electricity_emission",
    "Energieträger: Strom Endenergieverbrauch (kWh)": "energy_carrier_electricity_energy_consumption",
    "Nutzungsart: Gewerbe Anzahl": "usage_type_commercial_count",
    "Nutzungsart: Gewerbe Wärmebedarf (kWh)": "usage_type_commercial_heat_demand",
    "Nutzungsart: Gewerbe CO₂-Emission (t CO₂-Äq.)": "usage_type_commercial_emission",
    "Nutzungsart: Gewerbe Endenergieverbrauch (kWh)": "usage_type_commercial_energy_consumption",
    "Nutzungsart: Öffentliche Hand Anzahl": "usage_type_public_sector_count",
    "Nutzungsart: Öffentliche Hand Wärmebedarf (kWh)": "usage_type_public_sector_heat_demand",
    "Nutzungsart: Öffentliche Hand CO₂-Emission (t CO₂-Äq.)": "usage_type_public_sector_emission",
    "Nutzungsart: Öffentliche Hand Endenergieverbrauch (kWh)": "usage_type_public_sector_energy_consumption",
    "Nutzungsart: Sonstiges Anzahl": "usage_type_other_count",
    "Nutzungsart: Sonstiges Wärmebedarf (kWh)": "usage_type_other_heat_demand",
    "Nutzungsart: Sonstiges CO₂-Emission (t CO₂-Äq.)": "usage_type_other_emission",
    "Nutzungsart: Sonstiges Endenergieverbrauch (kWh)": "usage_type_other_energy_consumption",
    "Nutzungsart: Wohnen Anzahl": "usage_type_residential_count",
    "Nutzungsart: Wohnen Wärmebedarf (kWh)": "usage_type_residential_heat_demand",
    "Nutzungsart: Wohnen CO₂-Emission (t CO₂-Äq.)": "usage_type_residential_emission",
    "Nutzungsart: Wohnen Endenergieverbrauch (kWh)": "usage_type_residential_energy_consumption",
    "Heizungstechnik: Wärmepumpe (Strom) Anzahl": "heat_tech_heat_pump_electric_count",
    "Heizungstechnik: Wärmepumpe (Strom) Wärmebedarf (kWh)": "heat_tech_heat_pump_electric_heat_demand",
    "Heizungstechnik: Wärmepumpe (Strom) CO₂-Emission (t CO₂-Äq.)": "heat_tech_heat_pump_electric_emission",
    "Heizungstechnik: Wärmepumpe (Strom) Endenergieverbrauch (kWh)": "heat_tech_heat_pump_electric_energy_consumption",
    "Heizungstechnik: Wärmenetz Anzahl": "heat_tech_district_heating_count",
    "Heizungstechnik: Wärmenetz Wärmebedarf (kWh)": "heat_tech_district_heating_heat_demand",
    "Heizungstechnik: Wärmenetz CO₂-Emission (t CO₂-Äq.)": "heat_tech_district_heating_emission",
    "Heizungstechnik: Wärmenetz Endenergieverbrauch (kWh)": "heat_tech_district_heating_energy_consumption",
    "Heizungstechnik: Sonstiges Anzahl": "heat_tech_other_count",
    "Heizungstechnik: Sonstiges Wärmebedarf (kWh)": "heat_tech_other_heat_demand",
    "Heizungstechnik: Sonstiges CO₂-Emission (t CO₂-Äq.)": "heat_tech_other_emission",
    "Heizungstechnik: Sonstiges Endenergieverbrauch (kWh)": "heat_tech_other_energy_consumption",
    "Heizungstechnik: Pelletkessel Anzahl": "heat_tech_pellet_boiler_count",
    "Heizungstechnik: Pelletkessel Wärmebedarf (kWh)": "heat_tech_pellet_boiler_heat_demand",
    "Heizungstechnik: Pelletkessel CO₂-Emission (t CO₂-Äq.)": "heat_tech_pellet_boiler_emission",
    "Heizungstechnik: Pelletkessel Endenergieverbrauch (kWh)": "heat_tech_pellet_boiler_energy_consumption",
    "Heizungstechnik: Ölkessel Anzahl": "heat_tech_oil_boiler_count",
    "Heizungstechnik: Ölkessel Wärmebedarf (kWh)": "heat_tech_oil_boiler_heat_demand",
    "Heizungstechnik: Ölkessel CO₂-Emission (t CO₂-Äq.)": "heat_tech_oil_boiler_emission",
    "Heizungstechnik: Ölkessel Endenergieverbrauch (kWh)": "heat_tech_oil_boiler_energy_consumption",
    "Heizungstechnik: Nachtspeicher Anzahl": "heat_tech_storage_heater_count",
    "Heizungstechnik: Nachtspeicher Wärmebedarf (kWh)": "heat_tech_storage_heater_heat_demand",
    "Heizungstechnik: Nachtspeicher CO₂-Emission (t CO₂-Äq.)": "heat_tech_storage_heater_emission",
    "Heizungstechnik: Nachtspeicher Endenergieverbrauch (kWh)": "heat_tech_storage_heater_energy_consumption",
    "Heizungstechnik: Gaskessel Anzahl": "heat_tech_gas_boiler_count",
    "Heizungstechnik: Gaskessel Wärmebedarf (kWh)": "heat_tech_gas_boiler_heat_demand",
    "Heizungstechnik: Gaskessel CO₂-Emission (t CO₂-Äq.)": "heat_tech_gas_boiler_emission",
    "Heizungstechnik: Gaskessel Endenergieverbrauch (kWh)": "heat_tech_gas_boiler_energy_consumption",
    "Heizungstechnik: Gasetagenheizung Anzahl": "heat_tech_gas_room_heater_count",
    "Heizungstechnik: Gasetagenheizung Wärmebedarf (kWh)": "heat_tech_gas_room_heater_heat_demand",
    "Heizungstechnik: Gasetagenheizung CO₂-Emission (t CO₂-Äq.)": "heat_tech_gas_room_heater_emission",
    "Heizungstechnik: Gasetagenheizung Endenergieverbrauch (kWh)": "heat_tech_gas_room_heater_energy_consumption",
    "Wärmekatageorien: Kälte CO₂-Emission (t CO₂-Äq.)": "heat_cat_cooling_emission",
    "Wärmekatageorien: Kälte Endenergieverbrauch (kWh)": "heat_cat_cooling_energy_consumption",
    "Wärmekatageorien: Prozesskälte CO₂-Emission (t CO₂-Äq.)": "heat_cat_process_cooling_emission",
    "Wärmekatageorien: Prozesskälte Endenergieverbrauch (kWh)": "heat_cat_process_cooling_energy_consumption",
    "Wärmekatageorien: Prozesswärme CO₂-Emission (t CO₂-Äq.)": "heat_cat_process_heat_emission",
    "Wärmekatageorien: Prozesswärme Endenergieverbrauch (kWh)": "heat_cat_process_heat_energy_consumption",
    "Wärmekatageorien: Raumwärme CO₂-Emission (t CO₂-Äq.)": "heat_cat_space_heating_emission",
    "Wärmekatageorien: Raumwärme Endenergieverbrauch (kWh)": "heat_cat_space_heating_energy_consumption",
    "Potenzial: Abwärme Menge (kWh)": "potential_waste_heat_amount",
    "Potenzial: Abwasser Menge (kWh)": "potential_wastewater_amount",
    "Potenzial: Biomasse Menge (kWh)": "potential_biomass_amount",
    "Potenzial: Flussthermie Menge (kWh)": "potential_river_thermal_energy_amount",
    "Potenzial: Seethermie Menge (kWh)": "potential_sea_thermal_energy_amount"
  }
