##############################################################################
# This file holds configuration parameters for the creation of this dataset. #
##############################################################################

# Further custom configuration goes here
