##############################################################################
# This file holds configuration parameters for the creation of this dataset. #
##############################################################################

# Name of the dataset (used e.g. for report purposes)
title:
  Template dataset to show how things work

# Description of this dataset
description:
  Here comes a short description of the dataset.
  This is helpful for documentation and report generation purposes.

# Further custom configuration goes here
