##############################################################################
# This file holds configuration parameters for the creation of this dataset. #
##############################################################################

# Excel file
excel_file:
  sheet_name: "7. RBP"
  usecols: "A, G:S"
  skiprows: 3
  nrows: 230
  dtype:
    {
      "AGS": str
    }

# Years to be included (leave empty for all)
years:
  []
