##############################################################################
# This file holds configuration parameters for the creation of this dataset. #
##############################################################################

# If true, the conditions from "tags" are used as filters (e.g.
# ["building", "yes"] results in building=yes)
# If false, the keys from "tags" are selected but no further conditions apply
use_conditions: false

# Tags/conditions to include (format: [tag, value]))
tags:
  [
    ["building", "*"],
  ]

# Intermediate and output layer name
layer_name: "osm_buildings"
