solar-pv: "#e2c319"
wind-onshore: "#19c5e5"
hydro-reservoir: "#4a19e5"
hydro-ror: "#6d19e5"
h2-gt: "#75CCF0"
ch4-gt: "#71EFA4"

electricity-large_scale_battery: "#b41de6"
electricity-small_scale_battery: "#c453eb"

h2-cavern: "#19e5c0"
bev_charging: "#e55c19"

electricity-shortage: "#DADADA"

electricity-demand_hh: "#3e89f4"
electricity-demand_gdh: "#3e89f4"
electricity-demand_ind: "#3e89f4"
electricity-export: "#737a8c"
electricity-import: "#737a8c"
electricity-bev_charging: "#e55c19"

h2-bpchp_central: "#0F8A8A"
h2-bpchp_decentral: "#73B0AF"
h2-extchp_central: "#13ACAC"
h2-extchp_decentral: "#7DC8C7"
ch4-bpchp_central: "#128E10"
ch4-bpchp_decentral: "#74B465"
ch4-extchp_central: "#c0e519"
ch4-extchp_decentral: "#DAEE78"

heat_central-demand_hh: "#ff0800"
heat_central-demand_cts: "#ff0800"
heat_central-demand_ind: "#ff0800"
heat_central-excess: "#DBDBDB"
heat_central-shortage: "#DBDBDB"
heat_central-storage: "#e2c319"
heat_decentral-demand_hh: "#f2740a"
heat_decentral-demand_cts: "#f2740a"
heat_decentral-demand_ind: "#f2740a"
heat_decentral-excess: "#DBDBDB"
heat_decentral-shortage: "#DBDBDB"
heat_decentral-storage: "#e2c319"

ch4-boiler: "#e5194d"
electricity-heatpump_central: "#9912A1"
electricity-heatpump_decentral: "#f288e3"
electricity-pth: "#e58a19"

ch4-excess: "#DBDBDB"

electricity-electrolyzer: "#15B2BC"
ch4: "#bcf927"

other: "#7f7f7f"

ch4-import: "#cfcfcf"
h2-import: "#3B5054"
h2-demand: "#00fed0"

wind-offshore: "#73baec"
biomass: "#2ca02c"
biomass-biogas_plant: "#7ec073"
biomass-shortage: "#DBDBDB"
biogas: "#55844d"
biogas-biogas_upgrading_plant: "#8cac85"
biogas-shortage: "#DBDBDB"
biogas-bpchp_central: "#b7cbb2"
biogas-bpchp_decentral: "#cfdccb"
wood: "#754632"
wood-shortage: "#DBDBDB"
wood-extchp_central: "#92583F"
wood-extchp_decentral: "#a48070"
hard coal: "black"
lignite: "saddlebrown"
lignite-shortage: "#DBDBDB"
oil: "#9467bd"
nuclear: "pink"
