##############################################################################
# This file holds configuration parameters for the creation of this dataset. #
##############################################################################

# Household demand: years to create demand prognoses for
hh_electricity_demand:
  years:
    [
      2022,
      2045
    ]
