##############################################################################
# This file holds configuration parameters for the creation of this dataset. #
##############################################################################

# Name of the dataset (used e.g. for report purposes)
title:
  OpenStreetMap forests

# Description of this dataset
description:
  OSM data filtered for forests.

# Tags to include
tags:
  [
    ["landuse", "forest"],
    ["natural", "wood"],
  ]
