##############################################################################
# This file holds configuration parameters for the creation of this dataset. #
##############################################################################

# datasets to be copied from raw dataset
datasets:
  [
    "Agri-PV-Potenziale_Gesamt_100x100_EPSG3035",
    "Agri-PV-Potenziale_SQR_50-70_100x100_EPSG3035"
  ]
