##############################################################################
# This file holds configuration parameters for the creation of this dataset. #
##############################################################################

# Files to be extracted from raw dataset
files_extract:
  [
    "dr_cts_gas_timeseries_2011.csv",
    "dr_cts_power_demand_2022.csv",
    "dr_cts_power_timeseries_2022.csv",
    "dr_hh_gas_timeseries_2011.csv",
    "dr_hh_households_2011.csv",
    "dr_hh_population.csv",
    "dr_hh_power_demand_2022.csv",
    "dr_hh_power_timeseries_2022.csv",
    "dr_ind_gas_demand_2022.csv",
    "dr_ind_gas_timeseries_2011.csv",
    "dr_ind_gas_timeseries_2022.csv",
    "dr_ind_power_demand_2022.csv",
    "dr_ind_power_timeseries_2022.csv",
    "dr_temperature_ambient_2011.csv",
  ]
