import os

from snakemake.remote.HTTP import RemoteProvider as HTTPRemoteProvider
from digipipe.esys.esys.config.esys_conf import load_yaml

HTTP = HTTPRemoteProvider()


# Target rules
rule clean:
    shell:
        """
        rm -r ./results/*
        echo "Removed all results."
        """

# Include rules for intermediate steps
include: "snakemake_rules/build_datapackage.smk"
include: "snakemake_rules/optimization.smk"
include: "snakemake_rules/postprocessing.smk"
include: "snakemake_rules/create_empty_scalars.smk"

