##############################################################################
# This file holds configuration parameters for the creation of this dataset. #
##############################################################################

# Filter settings
layer: vg250_lan
attributes:
  {"NUTS": "nuts",
   "GEN": "name",
   "geometry": "geometry"}
attributes_filter:
  {"GF": 4}
