electricity: Electricity
heat_low_decentral: Heat (low, decentral)
heat_low_central: Heat (low, central)
heat_high: Heat (high)
residual_waste: Residual waste
biomass_solid: Solid biomass
biomass_gas: Biogas
h2: Hydrogen

# Electricity demands
electricity-demand_hh: Electricity demand (households)
electricity-demand_cts: Electricity demand (commercial, trade, services)
electricity-demand-mob: Electricity demand (mobility)
electricity-demand_ind: Electricity demand (industry)
# Heat low demands
heat_low_central-demand_hh: Heat (low, central) demand (households)
heat_low_central_demand_cts: Heat (low, central) demand (commercial, trade, services)
heat_low_central_demand_ind: Heat (low, central) demand (industry)
heat_low_decentral-demand_hh: Heat (low, decentral) demand (households)
heat_low_decentral_demand_cts: Heat (low, decentral) demand (commercial, trade, services)
heat_low_decentral_demand_ind: Heat (low, decentral) demand (industry)

# Heat high demands
heat_high-demand_ind: Heat (high) demand (industry)

# Imports
import-electricity: Electricity import

# Commodities
commodity_biomass_solid: Biomass (solid)
commodity_biomass_gas: Biogas
commodity_residual_waste: Residual waste
commodity-h2: Hydrogen

# Volatile
electricity-wind: Wind (onshore)
electricity-pv_ground: PV (ground-mounted)
electricity-pv_agri: PV (agriculture)
electricity-pv_rooftop: PV (rooftop)
heat_low_decentral_solarthermal_plant: Solar thermal collector (decentral)
heat_low_decentral_geothermal_plant: Geothermal plant (decentral)

# Conversion
biomass_solid_boiler_heat_high: Solid biomass boiler (high heat)
electricity_boiler_heat_high: Electric boiler (high heat)
h2_boiler_heat_high: Hydrogen boiler (high heat)
electricity_electrolyzer: Electrolyzer

# Heat pumps
electricity-heatpump_heat_low_central: Heat pump (low, central)
electricity-heatpump_heat_low_decentral: Heat pump (low, decentral)
electricity-heatpump_heat_high: Heat pump (high)

# CHP (combined heat and power)
biomass_solid_bpchp_heat_low_decentral: Solid biomass CHP (low, decentral)
biomass_solid_bpchp_heat_low_central: Solid biomass CHP (low, central)
biomass_solid_bpchp_heat_high: Solid biomass CHP (high)
biomass_gas_bpchp_heat_low_decentral: Biogas CHP (low, decentral)
biomass_gas_bpchp_heat_low_central: Biogas CHP (low, central)
biomass_gas_bpchp_heat_high: Biogas CHP (high)
h2_bpchp_heat_high: Hydrogen CHP (high)
residual_waste_bpchp_heat_high: Residual waste CHP (high)
residual_waste_bpchp_heat_low_central: Residual waste CHP (low, central)
biomass_solid_bpchp_heat_low_decentral: Solid biomass CHP (low, decentral)
biomass_solid_bpchp_heat_low_central: Solid biomass CHP (low, central)
biomass_gas_bpchp_heat_low_decentral: Biogas CHP (low, decentral)
biomass_gas_bpchp_heat_low_central: Biogas CHP (low, central)

# Storage
heat_low_decentral_storage: Heat storage (low, decentral)
electricity_storage_battery: Battery storage (electricity)

# Excess
h2-export: Hydrogen export
