##############################################################################
# This file holds configuration parameters for the creation of this dataset. #
##############################################################################

# Tags to include
tags:
  [
    ["landuse", "residential"],
    ["landuse", "forest"],
    ["natural", "wood"],
    ["military", "airfield"],
    ["aeroway", "aerodrome"],
  ]

geom_type: "multipolygons"
