##############################################################################
# This file holds configuration parameters for the creation of this dataset. #
##############################################################################

# Name of the dataset (used e.g. for report purposes)
title:
  OpenStreetMap filtered

# Description of this dataset
description:
  OSM data filtered for tags below, reprojected to LAEA Europe (EPSG:3035) and
  converted to Geopackage.

# Tags to include
tags:
  [
    ["landuse", "residential"],
    ["landuse", "forest"],
    ["natural", "wood"],
    ["military", "airfield"],
    ["aeroway", "aerodrome"],
  ]

geom_type: "multipolygons"
