##############################################################################
# This file holds configuration parameters for the creation of this dataset. #
##############################################################################

# Name of the dataset (used e.g. for report purposes)
title:
  BKG Verwaltungsgebiete 1:250 000 VG250 (Ebenen)

# Description of this dataset
description:
  Geodaten der Verwaltungsgebiete entpackt und in EPSG 3035 transformiert.
