##############################################################################
# This file holds configuration parameters for the creation of this dataset. #
##############################################################################

# Name of the dataset (used e.g. for report purposes)
title:
  MaStR power unit registry filtered

# Description of this dataset
description:
  Power units from MaStR extracted for selected technologies.

# Files to be extracted from raw dataset
files_extract:
  [
    "bnetza_mastr_biomass_raw.csv",
    "bnetza_mastr_combustion_raw.csv",
    "bnetza_mastr_electricity_consumer_raw.csv",
    "bnetza_mastr_gas_consumer_raw.csv",
    "bnetza_mastr_gas_producer_raw.csv",
    "bnetza_mastr_gas_storage_extended_raw.csv",
    "bnetza_mastr_grid_connections_raw.csv",
    "bnetza_mastr_gsgk_raw.csv",
    "bnetza_mastr_hydro_raw.csv",
    "bnetza_mastr_locations_extended_raw.csv",
    "bnetza_mastr_solar_raw.csv",
    "bnetza_mastr_storage_raw.csv",
    "bnetza_mastr_storage_unit_raw.csv",
    "bnetza_mastr_wind_raw.csv",
  ]
