##############################################################################
# This file holds configuration parameters for the creation of this dataset. #
##############################################################################

# Name of the dataset (used e.g. for report purposes)
title:
  Gemeinden der Region ABW

# Description of this dataset
description:
  Gemeinden der Region ABW aus Geodaten der Verwaltungsgebiete extrahiert und gefiltert.

# Filter settings
layer: vg250_gem
attributes:
  {"AGS": "ags",
   "NUTS": "nuts",
   "GEN": "name",
   "geometry": "geometry"}
attributes_filter:
  {"GF": 4,
   "NUTS": ["DEE01", "DEE05", "DEE0E"]}
